-- AlterTable
ALTER TABLE "CertificateTemplate" ADD COLUMN IF NOT EXISTS "templatePdfUrl" TEXT;
ALTER TABLE "CertificateTemplate" ADD COLUMN IF NOT EXISTS "nameXPercent" DOUBLE PRECISION NOT NULL DEFAULT 50;
ALTER TABLE "CertificateTemplate" ADD COLUMN IF NOT EXISTS "nameYPercent" DOUBLE PRECISION NOT NULL DEFAULT 42;
ALTER TABLE "CertificateTemplate" ADD COLUMN IF NOT EXISTS "nameFontSize" DOUBLE PRECISION NOT NULL DEFAULT 36;
ALTER TABLE "CertificateTemplate" ADD COLUMN IF NOT EXISTS "nameColor" TEXT NOT NULL DEFAULT '#1d4ed8';
