export type DesignRole =
  | "static"
  | "participantName"
  | "eventName"
  | "organizationName"
  | "date"
  | "certificateNumber"
  | "signatoryName"
  | "signatoryTitle"
  | "signature";

export type DesignElementType =
  | "text"
  | "rect"
  | "line"
  | "ellipse"
  | "icon"
  | "path";

export type DesignElement = {
  id: string;
  type: DesignElementType;
  x: number;
  y: number;
  width?: number;
  height?: number;
  text?: string;
  fontSize?: number;
  color?: string;
  align?: "left" | "center" | "right";
  bold?: boolean;
  letterSpacing?: number;
  fontStyle?: "serif" | "sans" | "script";
  role?: DesignRole;
  fill?: string;
  stroke?: string;
  strokeWidth?: number;
  opacity?: number;
  iconId?: string;
  path?: string;
  locked?: boolean;
};

export type CertificateDesign = {
  version: 1;
  width: number;
  height: number;
  background: string;
  elements: DesignElement[];
};

export type TemplatePreset = {
  id: string;
  name: string;
  description: string;
  thumbClass: string;
  create: () => CertificateDesign;
};

export const DESIGN_CANVAS = { width: 1123, height: 794 };

function baseMeta(
  elements: DesignElement[],
  background = "#ffffff",
): CertificateDesign {
  return {
    version: 1,
    width: DESIGN_CANVAS.width,
    height: DESIGN_CANVAS.height,
    background,
    elements,
  };
}

/** Classic centered white & gold frame */
export function createElegantStarterDesign(
  title = "CERTIFICATE",
  subtitle = "OF COMPLETION",
): CertificateDesign {
  return baseMeta([
    {
      id: "border-outer",
      type: "rect",
      x: 28,
      y: 28,
      width: 1067,
      height: 738,
      stroke: "#c9a227",
      strokeWidth: 3,
      fill: "transparent",
      locked: true,
    },
    {
      id: "border-inner",
      type: "rect",
      x: 42,
      y: 42,
      width: 1039,
      height: 710,
      stroke: "#d4af37",
      strokeWidth: 1.5,
      fill: "transparent",
      locked: true,
    },
    {
      id: "title",
      type: "text",
      x: 561,
      y: 110,
      text: title,
      fontSize: 52,
      color: "#1a1a1a",
      align: "center",
      bold: true,
      fontStyle: "serif",
      role: "static",
    },
    {
      id: "subtitle",
      type: "text",
      x: 561,
      y: 165,
      text: subtitle,
      fontSize: 16,
      color: "#4b5563",
      align: "center",
      letterSpacing: 6,
      role: "static",
    },
    {
      id: "given-to",
      type: "text",
      x: 561,
      y: 240,
      text: "This Certificate is given to:",
      fontSize: 15,
      color: "#374151",
      align: "center",
      role: "static",
    },
    {
      id: "participant-name",
      type: "text",
      x: 561,
      y: 310,
      text: "Participant Name",
      fontSize: 36,
      color: "#b8860b",
      align: "center",
      bold: true,
      fontStyle: "script",
      role: "participantName",
    },
    {
      id: "name-line",
      type: "line",
      x: 320,
      y: 330,
      width: 480,
      height: 0,
      stroke: "#d4af37",
      strokeWidth: 1.5,
    },
    {
      id: "body",
      type: "text",
      x: 561,
      y: 390,
      width: 680,
      text: "has successfully completed a professional training program. Their dedication and commitment to the learning process are truly commendable.",
      fontSize: 14,
      color: "#4b5563",
      align: "center",
      role: "static",
    },
    {
      id: "event-name",
      type: "text",
      x: 561,
      y: 450,
      text: "Event Name",
      fontSize: 18,
      color: "#111827",
      align: "center",
      bold: true,
      role: "eventName",
    },
    {
      id: "seal-center",
      type: "icon",
      iconId: "seal-gold",
      x: 521,
      y: 500,
      width: 80,
      height: 80,
    },
    {
      id: "sig-line-left",
      type: "line",
      x: 160,
      y: 640,
      width: 220,
      height: 0,
      stroke: "#9ca3af",
      strokeWidth: 1,
    },
    {
      id: "sig-left-name",
      type: "text",
      x: 270,
      y: 665,
      text: "Program Director",
      fontSize: 12,
      color: "#374151",
      align: "center",
      bold: true,
      role: "static",
    },
    {
      id: "signature",
      type: "text",
      x: 860,
      y: 615,
      text: "D. Gallego",
      fontSize: 28,
      color: "#111827",
      align: "center",
      fontStyle: "script",
      role: "signature",
    },
    {
      id: "sig-line-right",
      type: "line",
      x: 740,
      y: 640,
      width: 240,
      height: 0,
      stroke: "#111827",
      strokeWidth: 1.5,
    },
    {
      id: "md-name",
      type: "text",
      x: 860,
      y: 665,
      text: "DANIEL GALLEGO",
      fontSize: 13,
      color: "#111827",
      align: "center",
      bold: true,
      role: "signatoryName",
    },
    {
      id: "md-title",
      type: "text",
      x: 860,
      y: 685,
      text: "MD / CEO",
      fontSize: 11,
      color: "#6b7280",
      align: "center",
      role: "signatoryTitle",
    },
    {
      id: "date",
      type: "text",
      x: 561,
      y: 730,
      text: "Date",
      fontSize: 12,
      color: "#6b7280",
      align: "center",
      role: "date",
    },
  ]);
}

/** Black & gold appreciation — left swoosh + seal, MD signature bottom-right */
export function createAppreciationDesign(): CertificateDesign {
  return baseMeta([
    {
      id: "border",
      type: "rect",
      x: 36,
      y: 36,
      width: 1051,
      height: 722,
      stroke: "#c9a227",
      strokeWidth: 8,
      fill: "transparent",
      locked: true,
    },
    {
      id: "swoosh-black",
      type: "path",
      x: 0,
      y: 0,
      path: "M0,0 L220,0 C280,180 180,420 260,794 L0,794 Z",
      fill: "#111111",
      locked: true,
    },
    {
      id: "swoosh-gold",
      type: "path",
      x: 0,
      y: 0,
      path: "M180,0 C260,160 200,400 300,794 L220,794 C140,420 240,180 180,0 Z",
      fill: "#c9a227",
      locked: true,
    },
    {
      id: "seal-left",
      type: "icon",
      iconId: "seal-ribbon",
      x: 70,
      y: 70,
      width: 120,
      height: 140,
    },
    {
      id: "org",
      type: "text",
      x: 980,
      y: 70,
      text: "YOUR ORGANIZATION",
      fontSize: 11,
      color: "#111827",
      align: "right",
      bold: true,
      role: "organizationName",
    },
    {
      id: "title",
      type: "text",
      x: 620,
      y: 160,
      text: "CERTIFICATE",
      fontSize: 48,
      color: "#111111",
      align: "center",
      bold: true,
      fontStyle: "serif",
      role: "static",
    },
    {
      id: "subtitle",
      type: "text",
      x: 620,
      y: 210,
      text: "OF APPRECIATION",
      fontSize: 18,
      color: "#374151",
      align: "center",
      letterSpacing: 4,
      role: "static",
    },
    {
      id: "presented",
      type: "text",
      x: 620,
      y: 280,
      text: "THIS CERTIFICATE IS PRESENTED TO",
      fontSize: 13,
      color: "#111827",
      align: "center",
      bold: true,
      letterSpacing: 2,
      role: "static",
    },
    {
      id: "participant-name",
      type: "text",
      x: 620,
      y: 350,
      text: "Participant Name",
      fontSize: 42,
      color: "#c9a227",
      align: "center",
      fontStyle: "script",
      role: "participantName",
    },
    {
      id: "name-line",
      type: "line",
      x: 400,
      y: 370,
      width: 440,
      height: 0,
      stroke: "#c9a227",
      strokeWidth: 1.5,
    },
    {
      id: "body",
      type: "text",
      x: 620,
      y: 430,
      width: 520,
      text: "In recognition of outstanding achievements that significantly benefited the organization.",
      fontSize: 13,
      color: "#374151",
      align: "left",
      role: "static",
    },
    {
      id: "event-name",
      type: "text",
      x: 620,
      y: 490,
      text: "Event Name",
      fontSize: 16,
      color: "#111827",
      align: "center",
      bold: true,
      role: "eventName",
    },
    {
      id: "signature",
      type: "text",
      x: 820,
      y: 600,
      text: "D. Gallego",
      fontSize: 30,
      color: "#111111",
      align: "center",
      fontStyle: "script",
      role: "signature",
    },
    {
      id: "sig-line",
      type: "line",
      x: 700,
      y: 620,
      width: 240,
      height: 0,
      stroke: "#111111",
      strokeWidth: 1.5,
    },
    {
      id: "md-name",
      type: "text",
      x: 820,
      y: 650,
      text: "DANIEL GALLEGO",
      fontSize: 13,
      color: "#111111",
      align: "center",
      bold: true,
      role: "signatoryName",
    },
    {
      id: "md-title",
      type: "text",
      x: 820,
      y: 672,
      text: "MD / CEO",
      fontSize: 11,
      color: "#4b5563",
      align: "center",
      role: "signatoryTitle",
    },
    {
      id: "date",
      type: "text",
      x: 420,
      y: 720,
      text: "Date",
      fontSize: 12,
      color: "#6b7280",
      align: "left",
      role: "date",
    },
  ]);
}

/** Achievement — wreath + trophy accent */
export function createAchievementDesign(): CertificateDesign {
  return baseMeta([
    {
      id: "border-outer",
      type: "rect",
      x: 24,
      y: 24,
      width: 1075,
      height: 746,
      stroke: "#111827",
      strokeWidth: 2,
      fill: "transparent",
      locked: true,
    },
    {
      id: "border-gold",
      type: "rect",
      x: 36,
      y: 36,
      width: 1051,
      height: 722,
      stroke: "#d4af37",
      strokeWidth: 4,
      fill: "transparent",
      locked: true,
    },
    {
      id: "corner-tl",
      type: "icon",
      iconId: "corner-flourish",
      x: 48,
      y: 48,
      width: 90,
      height: 90,
    },
    {
      id: "corner-tr",
      type: "icon",
      iconId: "corner-flourish",
      x: 985,
      y: 48,
      width: 90,
      height: 90,
    },
    {
      id: "wreath-top",
      type: "icon",
      iconId: "wreath-gold",
      x: 501,
      y: 70,
      width: 120,
      height: 120,
    },
    {
      id: "title",
      type: "text",
      x: 561,
      y: 220,
      text: "CERTIFICATE",
      fontSize: 44,
      color: "#111827",
      align: "center",
      bold: true,
      fontStyle: "serif",
      role: "static",
    },
    {
      id: "subtitle",
      type: "text",
      x: 561,
      y: 265,
      text: "OF ACHIEVEMENT",
      fontSize: 16,
      color: "#b8860b",
      align: "center",
      letterSpacing: 5,
      role: "static",
    },
    {
      id: "presented",
      type: "text",
      x: 561,
      y: 320,
      text: "Proudly awarded to",
      fontSize: 14,
      color: "#4b5563",
      align: "center",
      role: "static",
    },
    {
      id: "participant-name",
      type: "text",
      x: 561,
      y: 380,
      text: "Participant Name",
      fontSize: 38,
      color: "#111827",
      align: "center",
      fontStyle: "script",
      role: "participantName",
    },
    {
      id: "name-line",
      type: "line",
      x: 340,
      y: 400,
      width: 440,
      height: 0,
      stroke: "#d4af37",
      strokeWidth: 1,
    },
    {
      id: "body",
      type: "text",
      x: 561,
      y: 450,
      width: 640,
      text: "for outstanding performance and dedication demonstrated throughout the program.",
      fontSize: 14,
      color: "#4b5563",
      align: "center",
      role: "static",
    },
    {
      id: "event-name",
      type: "text",
      x: 561,
      y: 510,
      text: "Event Name",
      fontSize: 17,
      color: "#111827",
      align: "center",
      bold: true,
      role: "eventName",
    },
    {
      id: "medal",
      type: "icon",
      iconId: "medal-gold",
      x: 531,
      y: 540,
      width: 60,
      height: 70,
    },
    {
      id: "signature",
      type: "text",
      x: 860,
      y: 640,
      text: "D. Gallego",
      fontSize: 26,
      color: "#111827",
      align: "center",
      fontStyle: "script",
      role: "signature",
    },
    {
      id: "sig-line",
      type: "line",
      x: 740,
      y: 658,
      width: 240,
      height: 0,
      stroke: "#111827",
      strokeWidth: 1.5,
    },
    {
      id: "md-name",
      type: "text",
      x: 860,
      y: 682,
      text: "DANIEL GALLEGO",
      fontSize: 12,
      color: "#111827",
      align: "center",
      bold: true,
      role: "signatoryName",
    },
    {
      id: "md-title",
      type: "text",
      x: 860,
      y: 702,
      text: "MD / Managing Director",
      fontSize: 11,
      color: "#6b7280",
      align: "center",
      role: "signatoryTitle",
    },
    {
      id: "date",
      type: "text",
      x: 200,
      y: 690,
      text: "Date",
      fontSize: 12,
      color: "#6b7280",
      align: "center",
      role: "date",
    },
  ]);
}

/** Clean participation template */
export function createParticipationDesign(): CertificateDesign {
  return baseMeta(
    [
      {
        id: "accent-bar",
        type: "rect",
        x: 0,
        y: 0,
        width: 1123,
        height: 18,
        fill: "#0f766e",
        locked: true,
      },
      {
        id: "accent-bar-bottom",
        type: "rect",
        x: 0,
        y: 776,
        width: 1123,
        height: 18,
        fill: "#0f766e",
        locked: true,
      },
      {
        id: "title",
        type: "text",
        x: 561,
        y: 120,
        text: "CERTIFICATE",
        fontSize: 46,
        color: "#0f766e",
        align: "center",
        bold: true,
        fontStyle: "serif",
        role: "static",
      },
      {
        id: "subtitle",
        type: "text",
        x: 561,
        y: 170,
        text: "OF PARTICIPATION",
        fontSize: 16,
        color: "#374151",
        align: "center",
        letterSpacing: 5,
        role: "static",
      },
      {
        id: "laurel",
        type: "icon",
        iconId: "laurel-pair",
        x: 461,
        y: 200,
        width: 200,
        height: 50,
      },
      {
        id: "given-to",
        type: "text",
        x: 561,
        y: 280,
        text: "This is to certify that",
        fontSize: 15,
        color: "#4b5563",
        align: "center",
        role: "static",
      },
      {
        id: "participant-name",
        type: "text",
        x: 561,
        y: 350,
        text: "Participant Name",
        fontSize: 36,
        color: "#0f766e",
        align: "center",
        bold: true,
        role: "participantName",
      },
      {
        id: "body",
        type: "text",
        x: 561,
        y: 420,
        width: 680,
        text: "has successfully participated in the program and demonstrated valuable engagement.",
        fontSize: 14,
        color: "#4b5563",
        align: "center",
        role: "static",
      },
      {
        id: "event-name",
        type: "text",
        x: 561,
        y: 480,
        text: "Event Name",
        fontSize: 18,
        color: "#111827",
        align: "center",
        bold: true,
        role: "eventName",
      },
      {
        id: "signature",
        type: "text",
        x: 860,
        y: 620,
        text: "D. Gallego",
        fontSize: 28,
        color: "#111827",
        align: "center",
        fontStyle: "script",
        role: "signature",
      },
      {
        id: "sig-line",
        type: "line",
        x: 740,
        y: 640,
        width: 240,
        height: 0,
        stroke: "#0f766e",
        strokeWidth: 1.5,
      },
      {
        id: "md-name",
        type: "text",
        x: 860,
        y: 665,
        text: "DANIEL GALLEGO",
        fontSize: 12,
        color: "#111827",
        align: "center",
        bold: true,
        role: "signatoryName",
      },
      {
        id: "md-title",
        type: "text",
        x: 860,
        y: 685,
        text: "MD / Director",
        fontSize: 11,
        color: "#6b7280",
        align: "center",
        role: "signatoryTitle",
      },
      {
        id: "date",
        type: "text",
        x: 220,
        y: 665,
        text: "Date",
        fontSize: 12,
        color: "#6b7280",
        align: "center",
        role: "date",
      },
    ],
    "#f8fafc",
  );
}

export const TEMPLATE_PRESETS: TemplatePreset[] = [
  {
    id: "elegant",
    name: "White & Gold Elegant",
    description: "Classic framed completion certificate",
    thumbClass: "elegant",
    create: () => createElegantStarterDesign(),
  },
  {
    id: "appreciation",
    name: "Black & Gold Appreciation",
    description: "Left swoosh, seal, MD signature right",
    thumbClass: "appreciation",
    create: createAppreciationDesign,
  },
  {
    id: "achievement",
    name: "Achievement Laurel",
    description: "Corners, wreath, medal accents",
    thumbClass: "achievement",
    create: createAchievementDesign,
  },
  {
    id: "participation",
    name: "Teal Participation",
    description: "Clean modern participation layout",
    thumbClass: "participation",
    create: createParticipationDesign,
  },
];

export type DesignIconDef = {
  id: string;
  label: string;
  category: "seals" | "wreaths" | "medals" | "corners" | "shapes";
  defaultWidth: number;
  defaultHeight: number;
};

export const DESIGN_ICONS: DesignIconDef[] = [
  { id: "seal-gold", label: "Gold seal", category: "seals", defaultWidth: 90, defaultHeight: 90 },
  { id: "seal-ribbon", label: "Seal + ribbon", category: "seals", defaultWidth: 100, defaultHeight: 120 },
  { id: "seal-red", label: "Red ribbon seal", category: "seals", defaultWidth: 90, defaultHeight: 110 },
  { id: "wreath-gold", label: "Gold wreath", category: "wreaths", defaultWidth: 110, defaultHeight: 110 },
  { id: "wreath-black", label: "Black wreath", category: "wreaths", defaultWidth: 110, defaultHeight: 110 },
  { id: "laurel-pair", label: "Laurel branches", category: "wreaths", defaultWidth: 200, defaultHeight: 50 },
  { id: "medal-gold", label: "Gold medal", category: "medals", defaultWidth: 60, defaultHeight: 80 },
  { id: "trophy-wreath", label: "Trophy wreath", category: "medals", defaultWidth: 100, defaultHeight: 100 },
  { id: "shield-wreath", label: "Shield emblem", category: "medals", defaultWidth: 90, defaultHeight: 100 },
  { id: "corner-flourish", label: "Corner ornament", category: "corners", defaultWidth: 90, defaultHeight: 90 },
];
